name: Lock Closed Issues

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  issues: write

jobs:
  action:
    if: github.repository == 'kolibryjs/kolibry-vue-plugin'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-inactive-days: "14"
          #issue-comment: |
          #  This issue has been locked since it has been closed for more than 14 days.
          #
          #  If you have found a concrete bug or regression related to it, please open a new [bug report](https://github.com/kolibryjs/kolibry-vue-plugin/issues/new/choose) with a reproduction against the latest Kolibry version. If you have any other comments you should join the chat at [Kolibry Land](https://discord.kolibry.zip) or create a new [discussion](https://github.com/kolibryjs/kolibry-vue-plugin/discussions).
          issue-lock-reason: ""
          process-only: "issues"
